### ISSUE TITLE
index 253 is out of bounds for axis 0 with size 32 on nvidia A100

### ISSUE THREAD

**Issue by 4r33x** [WincerChan/SolVanityCL#18]
Got this error on Debian\nvidia :C

python main.py search-pubkey --starts-with AAAAAAA
[INFO 2024-11-14 03:07:32,132] Searching Solana pubkey that starts with 'AAAAAAA' and ends with ''
[INFO 2024-11-14 03:07:32,434] Searching with 1 OpenCL devices
[ERROR 2024-11-14 03:07:32,497] clGetDeviceIDs failed: INVALID_DEVICE
Traceback (most recent call last):
  File "SolVanityCL/main.py", line 119, in multi_gpu_init
    searcher = Searcher(
  File "SolVanityCL/main.py", line 155, in __init__
    device_ids = get_all_gpu_devices()
  File "SolVanityCL/main.py", line 98, in get_all_gpu_devices
    devices = [
  File "SolVanityCL/main.py", line 101, in <listcomp>
    for device in platform.get_devices(device_type=cl.device_type.GPU)
pyopencl._cl.LogicError: clGetDeviceIDs failed: INVALID_DEVICE
SolVanityCL/main.py:50: RuntimeWarning: overflow encountered in scalar subtract
  carry_index = 0 - self.iteration_bytes
Traceback (most recent call last):
  File "SolVanityCL/main.py", line 337, in <module>
    cli()
  File ".conda/envs/van/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File ".conda/envs/van/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File ".conda/envs/van/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".conda/envs/van/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".conda/envs/van/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File ".conda/envs/van/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "SolVanityCL/main.py", line 317, in search_pubkey
    setting.increase_key32()
  File "SolVanityCL/main.py", line 51, in increase_key32
    if (new_key32[carry_index] < self.key32[carry_index]) and new_key32[
IndexError: index 253 is out of bounds for axis 0 with size 32

**Comment by 4r33x** [comment]
Seems like conda issue....
