### ISSUE TITLE
AMD Radeon RX 7600 + Windows not working

### ISSUE THREAD

**Issue by Sayrix** [WincerChan/SolVanityCL#4]
```
[INFO 2024-05-17 21:21:23,920] Searching Solana pubkey that starts with 'SoL' and ends with ''
[INFO 2024-05-17 21:21:23,993] Searching with 2 OpenCL devices
Traceback (most recent call last):
  File "C:\Users\Sayrix\Desktop\SolVanityCL-master\main.py", line 253, in <module>
    cli()
  File "C:\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sayrix\Desktop\SolVanityCL-master\main.py", line 206, in search_pubkey
    searcher = Searcher(
               ^^^^^^^^^
  File "C:\Users\Sayrix\Desktop\SolVanityCL-master\main.py", line 60, in __init__
    program = cl.Program(context, kernel_source).build()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pyopencl\__init__.py", line 516, in build
    self._prg, was_cached = self._build_and_catch_errors(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pyopencl\__init__.py", line 564, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'gfx1036' on 'AMD Accelerated Parallel Processing' at 0x19efd0fdb70>:

C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:71:11: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_0(__generic fe h) {
          ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2271:23: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul__contant2(__generic fe h, const __generic fe f, constant fe g) {
                      ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2271:45: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul__contant2(__generic fe h, const __generic fe f, constant fe g) {
                                            ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2491:23: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul__contant1(__generic fe h, constant fe f, const __generic fe g) {
                      ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2491:60: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul__contant1(__generic fe h, constant fe f, const __generic fe g) {
                                                           ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2712:13: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
            ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2712:35: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                  ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2712:57: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                                        ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2933:13: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
            ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2933:35: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                  ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2933:57: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                                        ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2977:13: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
            ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2977:35: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                  ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:2977:57: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                                        ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:3021:41: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_tobytes(unsigned char *s, const __generic fe h) {
                                        ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:3142:11: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_1(__generic fe h) {
          ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:3173:24: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_cmov__constant(__generic fe f, constant fe g, unsigned int b) {
                       ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:3229:14: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_cmov(__generic fe f, const __generic fe g, unsigned int b) {
             ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-76152e\input\CompileSource:3229:36: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_cmov(__generic fe f, const __generic fe g, unsigned int b) {
                                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Error: Failed to compile source (from CL or HIP source to LLVM IR).
===========================================================================
Build on <pyopencl.Device 'gfx1102' on 'AMD Accelerated Parallel Processing' at 0x19efd206f60>:

C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:71:11: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_0(__generic fe h) {
          ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2271:23: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul__contant2(__generic fe h, const __generic fe f, constant fe g) {
                      ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2271:45: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul__contant2(__generic fe h, const __generic fe f, constant fe g) {
                                            ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2491:23: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul__contant1(__generic fe h, constant fe f, const __generic fe g) {
                      ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2491:60: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul__contant1(__generic fe h, constant fe f, const __generic fe g) {
                                                           ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2712:13: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
            ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2712:35: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                  ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2712:57: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_mul(__generic fe h, const __generic fe f, const __generic fe g) {
                                                        ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2933:13: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
            ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2933:35: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                  ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2933:57: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_sub(__generic fe h, const __generic fe f, const __generic fe g) {
                                                        ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2977:13: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
            ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2977:35: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                  ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:2977:57: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_add(__generic fe h, const __generic fe f, const __generic fe g) {
                                                        ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:3021:41: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_tobytes(unsigned char *s, const __generic fe h) {
                                        ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:3142:11: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_1(__generic fe h) {
          ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:3173:24: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_cmov__constant(__generic fe f, constant fe g, unsigned int b) {
                       ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:3229:14: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_cmov(__generic fe f, const __generic fe g, unsigned int b) {
             ^
C:\Users\Sayrix\AppData\Local\Temp\comgr-506f0e\input\CompileSource:3229:36: error: OpenCL C version 1.2 does not support the '__generic' type qualifier
void fe_cmov(__generic fe f, const __generic fe g, unsigned int b) {
                                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Error: Failed to compile source (from CL or HIP source to LLVM IR).

(options: -I C:\Python312\Lib\site-packages\pyopencl\cl)
(source saved as C:\Users\Sayrix\AppData\Local\Temp\tmputzjaj1j.cl)
```

**Comment by WincerChan** [comment]
Thank you for your testing. In the latest commit (https://github.com/WincerChan/SolVanityCL/pull/5), although I fixed the compilation errors and tested on my Windows + Vega56 device, I found that the output was not as expected. There may be other issues that I haven't discovered yet and need further confirmation.

However, I do not recommend running on AMD GPU devices, as they are much less efficient compared to Nvidia devices.

**Comment by Sayrix** [comment]
Hi, thanks for your quick fix, it works but partially. If i want to use my AMD gpu is because i only have that, in addition 9 MH/s for 180~200 watt is not bad. Here is all the bugs that i found:
1. I can't find more than 1 address at once, what it does is that it first find 1 address correct, and then it always gives me this address: 4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS and then it re gives me the address found.
```
> python main.py search-pubkey --select-device --starts-with a --count 100
[INFO 2024-05-18 17:27:00,991] Searching Solana pubkey that starts with 'a' and ends with ''
Choose platform:
[0] <pyopencl.Platform 'AMD Accelerated Parallel Processing' at 0x7fff1506d000>
Choice [0]:0
Choose device(s):
[0] <pyopencl.Device 'gfx1036' on 'AMD Accelerated Parallel Processing' at 0x298759ed020>
[1] <pyopencl.Device 'gfx1102' on 'AMD Accelerated Parallel Processing' at 0x29875af8f80>
Choice, comma-separated [0]:1
Set the environment variable PYOPENCL_CTX='0:1' to avoid being asked again.
[INFO 2024-05-18 17:27:03,164] Searching with 1 OpenCL devices
C:\Python312\Lib\site-packages\pyopencl\cache.py:495: CompilerWarning: Built kernel retrieved from cache. Original from-source build had warnings:
Build on <pyopencl.Device 'gfx1102' on 'AMD Accelerated Parallel Processing' at 0x29875af8f80> succeeded, but said:

warning: argument unused during compilation: '-I C:\Python312\Lib\site-packages\pyopencl\cl' [-Wunused-command-line-argument]
1 warning generated.

  _create_built_program_from_source_cached(
[INFO 2024-05-18 17:27:05,386] Speed: 8.93 MH/s
[INFO 2024-05-18 17:27:05,386] Found: apCyK29n2qYHETTJr6jUKshm95vnwctg8rfL3U7bb4A
[INFO 2024-05-18 17:27:07,363] Speed: 8.95 MH/s
[INFO 2024-05-18 17:27:07,364] Found: 4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS
[INFO 2024-05-18 17:27:09,332] Speed: 8.99 MH/s
[INFO 2024-05-18 17:27:09,332] Found: apCyK29n2qYHETTJr6jUKshm95vnwctg8rfL3U7bb4A
[INFO 2024-05-18 17:27:11,300] Speed: 8.99 MH/s
[INFO 2024-05-18 17:27:11,301] Found: 4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS
[INFO 2024-05-18 17:27:13,254] Speed: 9.06 MH/s
[INFO 2024-05-18 17:27:13,255] Found: apCyK29n2qYHETTJr6jUKshm95vnwctg8rfL3U7bb4A
[INFO 2024-05-18 17:27:15,212] Speed: 9.04 MH/s
[INFO 2024-05-18 17:27:15,212] Found: 4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS
[INFO 2024-05-18 17:27:17,185] Speed: 8.97 MH/s
[INFO 2024-05-18 17:27:17,186] Found: apCyK29n2qYHETTJr6jUKshm95vnwctg8rfL3U7bb4A
[INFO 2024-05-18 17:27:19,143] Speed: 9.05 MH/s
[INFO 2024-05-18 17:27:19,144] Found: 4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS

Aborted!
```
2. It seems that if the address found is not found when starting, it always gives me 4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS for example, if i choose abc it will be find, but if i choose abcd, it gives me 4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS
```
 python main.py search-pubkey --select-device --starts-with abc --count 100
[INFO 2024-05-18 17:31:35,110] Searching Solana pubkey that starts with 'abc' and ends with ''
Choose platform:
[0] <pyopencl.Platform 'AMD Accelerated Parallel Processing' at 0x7fff1506d000>
Choice [0]:0
Choose device(s):
[0] <pyopencl.Device 'gfx1036' on 'AMD Accelerated Parallel Processing' at 0x1eece05ef60>
[1] <pyopencl.Device 'gfx1102' on 'AMD Accelerated Parallel Processing' at 0x1eece0606d0>
Choice, comma-separated [0]:1
Set the environment variable PYOPENCL_CTX='0:1' to avoid being asked again.
[INFO 2024-05-18 17:31:37,932] Searching with 1 OpenCL devices
C:\Python312\Lib\site-packages\pyopencl\cache.py:495: CompilerWarning: Built kernel retrieved from cache. Original from-source build had warnings:
Build on <pyopencl.Device 'gfx1102' on 'AMD Accelerated Parallel Processing' at 0x1eece0606d0> succeeded, but said:

warning: argument unused during compilation: '-I C:\Python312\Lib\site-packages\pyopencl\cl' [-Wunused-command-line-argument]
1 warning generated.

  _create_built_program_from_source_cached(
[INFO 2024-05-18 17:31:40,186] Speed: 8.95 MH/s
[INFO 2024-05-18 17:31:40,186] Found: abczP1w2ViHgAHZh98zMrq6v2EMPJ7y7HJ2pnjkCRZS
[INFO 2024-05-18 17:31:42,150] Speed: 9.01 MH/s
[INFO 2024-05-18 17:31:42,150] Found: 4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS

Aborted!
```

```
> python main.py search-pubkey --select-device --starts-with abcd --count 100
[INFO 2024-05-18 17:31:58,404] Searching Solana pubkey that starts with 'abcd' and ends with ''
Choose platform:
[0] <pyopencl.Platform 'AMD Accelerated Parallel Processing' at 0x7fff1506d000>
Choice [0]:0
Choose device(s):
[0] <pyopencl.Device 'gfx1036' on 'AMD Accelerated Parallel Processing' at 0x1dcdcbd4f60>
[1] <pyopencl.Device 'gfx1102' on 'AMD Accelerated Parallel Processing' at 0x1dcdcbd66d0>
Choice, comma-separated [0]:1
Set the environment variable PYOPENCL_CTX='0:1' to avoid being asked again.
[INFO 2024-05-18 17:32:01,322] Searching with 1 OpenCL devices
C:\Python312\Lib\site-packages\pyopencl\cache.py:495: CompilerWarning: Built kernel retrieved from cache. Original from-source build had warnings:
Build on <pyopencl.Device 'gfx1102' on 'AMD Accelerated Parallel Processing' at 0x1dcdcbd66d0> succeeded, but said:

warning: argument unused during compilation: '-I C:\Python312\Lib\site-packages\pyopencl\cl' [-Wunused-command-line-argument]
1 warning generated.

  _create_built_program_from_source_cached(
[INFO 2024-05-18 17:32:03,565] Speed: 8.94 MH/s
[INFO 2024-05-18 17:32:05,439] Speed: 8.95 MH/s
[INFO 2024-05-18 17:32:05,440] Found: 4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS
[INFO 2024-05-18 17:32:07,408] Speed: 8.99 MH/s
[INFO 2024-05-18 17:32:07,409] Found: 4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS

Aborted!
```

Python 3.12.0
AMD Radeon RX 7600 + Integrated AMD GPU from my Ryzen 7 7700 (which by the way don't works, so i have to choose the gpu every time i start the script)
Windows 11 23H2 22631.3593

**Comment by WincerChan** [comment]
Thank you for your detailed testing. I need some time to investigate. 

Additionally, if you don't want to choose the device every time, you can avoid being asked again by setting the environment variable PYOPENCL_CTX='0:1'.

**Comment by Sayrix** [comment]
If you need me to try your code let me know!

**Comment by WincerChan** [comment]
I have fixed the issue where the output on your device was always 4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS. You can verify it on the [windows_patched branch](https://github.com/WincerChan/SolVanityCL/tree/windows_patched).

It still doesn't produce the expected output on my Windows device, but based on your previous logs, it seems to be partially working. Could you please verify it again?

**Comment by Sayrix** [comment]
Hey thanks! It seems to work, Do you know if i can search multiple address at once ? like "--starts-with 1 --starts-with 2 --starts-with 3 ...". About the --count option it seems to work on my side.

```
python .\main.py search-pubkey --select-device --starts-with 1 --starts-with 2 --starts-with 3 --count 100
[INFO 2024-05-19 11:46:49,602] Searching Solana pubkey that starts with '3' and ends with ''
[INFO 2024-05-19 11:46:49,625] Searching with 1 OpenCL devices
C:\Python312\Lib\site-packages\pyopencl\cache.py:417: CompilerWarning: From-source build succeeded, but resulted in non-empty logs:
Build on <pyopencl.Device 'gfx1102' on 'AMD Accelerated Parallel Processing' at 0x1b4fe6346e0> succeeded, but said:

warning: argument unused during compilation: '-I C:\Python312\Lib\site-packages\pyopencl\cl' [-Wunused-command-line-argument]
1 warning generated.

  prg.build(options_bytes, [devices[i] for i in to_be_built_indices])
[INFO 2024-05-19 11:46:59,849] Speed: 9.14 MH/s
[INFO 2024-05-19 11:46:59,849] Found: 3ZuzS68wo6x7PVLqP2n7huDV5RnnSZvWvES1NGRy5kaR
[INFO 2024-05-19 11:47:01,778] Speed: 9.23 MH/s
[INFO 2024-05-19 11:47:01,778] Found: 3wQ33YxB7jhR62knYDbNrjoQNUb9hxCgML9MShewB2Km
[INFO 2024-05-19 11:47:03,708] Speed: 9.17 MH/s
[INFO 2024-05-19 11:47:03,709] Found: 3WfgrJv7mUdgNvn62jh64usvjRAi3pEj7REdBtarqUpV
[INFO 2024-05-19 11:47:05,639] Speed: 9.18 MH/s
[INFO 2024-05-19 11:47:05,639] Found: 3GuY9HT2Akwv9ULUU8Y68B2fQhqG7jbZMzeH48NcZxfY
[INFO 2024-05-19 11:47:07,568] Speed: 9.17 MH/s
[INFO 2024-05-19 11:47:07,569] Found: 3bti2XdoZc3j5fcUrb14Xqk7AG9rjkiEMy2p388m932M
```

**Comment by WincerChan** [comment]
You cannot specify multiple `starts-with` parameters simultaneously; only the last one will be used. 
If you need to specify multiple prefixes or suffixes, please run the program separately with each parameter.

**Comment by Sayrix** [comment]
Okay. Can you check #6 there is a new bug found. And thanks for your fixes!
